
name: Update Readme
on:
  push:
    branches: 
      - master
    paths:
    - "src/main/java/carpetextra/CarpetExtraSettings.java"
    - "README-header.md"
jobs:
  Rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Carpet extra sources
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Generate RulePrinter class
        run: |
          cd src/main/java/carpetextra/utils
          echo "
          package carpetextra.utils;
          import carpetextra.CarpetExtraServer;
          import carpet.CarpetServer;
          import carpet.settings.SettingsManager;
          import net.fabricmc.loader.api.entrypoint.PreLaunchEntrypoint;
          import java.lang.System;
          public class RulePrinter implements PreLaunchEntrypoint {
            @Override
            public void onPreLaunch() {
                CarpetExtraServer.noop();
                CarpetServer.onGameStarted();
                CarpetServer.settingsManager.printAllRulesToLog(\"extras\");
                System.exit(0);
            }
          }
          " > RulePrinter.java
          cd ../../../../../
      - name: Replace fabric.mod.json
        run: |
          cd src/main/resources
          rm fabric.mod.json
          echo '
          {
            "schemaVersion": 1,
            "id": "carpetextra",
            "version": "1.4.11",
            "entrypoints": {
              "preLaunch": [ "carpetextra.utils.RulePrinter" ]
            }
           }' > fabric.mod.json
          cd ../../../
      - name: Run solution
        run: |
          chmod +x gradlew
          ./gradlew runServer > settings-toProccess.txt
      - name: Proccess Gradle log into a pretty readme page
        run: |
          cat README-header.md > README.md
          from1="# Carpet Mod Settings";
          File=settings-toProccess.txt
          if grep -q "Deprecated Gradle features" "$File"; then # Happens after update to Gradle 6
            to2="Deprecated Gradle features";
          else
            to2="BUILD SUCCESSFUL"
          fi
          a="$(cat settings-toProccess.txt)";a="$(echo "${a#*"$from1"}")"; echo "${a%%"$to2"*}" >> README.md
      - name: Commit updated Readme page
        continue-on-error: true
        run: |
          git add README.md
          git config --global user.name 'github-actions[bot]' # Looks better than "github-actions-bot"
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update Readme for '${{ github.event.head_commit.message }}'"
          git push
